spring.application.name=eureka-service
server.port=8761

#bach maysjlch rasso f eureka
eureka.client.register-with-eureka=false

#bach mayjibch l registry dyal services li kaynin f eureka
euriea.client.fetch-registry=false




